<?php

use Carbon\Carbon;

return [
    [
        'title' => 'Home',
        'url' => route('index'),
        'order' => 1,
        'type' => null,
        'type_id' => 0,
        'has_child' => 0,
        'parent_id' => 0,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Berita',
        'url' => route('frontend.berita.index'),
        'order' => 2,
        'type' => null,
        'type_id' => 0,
        'has_child' => 0,
        'parent_id' => 0,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Galeri',
        'url' => route('galeri'),
        'order' => 3,
        'type' => null,
        'type_id' => 0,
        'has_child' => 0,
        'parent_id' => 0,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Profil',
        'url' => '#',
        'order' => 4,
        'type' => 'page',
        'type_id' => 1,
        'has_child' => 1,
        'parent_id' => 0,
        'child' => json_encode([5, 6, 7, 8]),
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Gambaran Umum',
        'url' => route('frontend.getPage', 'gambaran-umum'),
        'type' => 'page',
        'type_id' => 2,
        'order' => 99,
        'has_child' => 0,
        'parent_id' => 4,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Visi Misi',
        'url' => route('frontend.getPage', 'visi-misi'),
        'type' => 'page',
        'type_id' => 3,
        'order' => 99,
        'has_child' => 0,
        'parent_id' => 4,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Struktur Organisasi',
        'url' => route('frontend.getPage', 'struktur-organisasi'),
        'type' => 'page',
        'type_id' => 4,
        'order' => 99,
        'has_child' => 0,
        'parent_id' => 4,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Sambutan Kepala Dinas',
        'url' => route('frontend.getPage', 'sambutan-kepala-dinas'),
        'type' => 'page',
        'type_id' => 5,
        'order' => 99,
        'has_child' => 0,
        'parent_id' => 4,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Bidang Organisasi',
        'url' => '#',
        'order' => 5,
        'type' => 'page',
        'type_id' => 6,
        'has_child' => 1,
        'parent_id' => 0,
        'child' => json_encode([10, 11, 12, 13, 14, 15]),
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Bidang Sekretariat',
        'url' => route('frontend.getCategory', 'bidang-sekretariat'),
        'type' => 'category',
        'type_id' => 1,
        'order' => 99,
        'has_child' => 0,
        'parent_id' => 9,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Bidang Bina Marga',
        'url' => route('frontend.getCategory', 'bidang-bina-marga'),
        'type' => 'category',
        'type_id' => 2,
        'order' => 99,
        'has_child' => 0,
        'parent_id' => 9,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Bidang Tata Ruang',
        'url' => route('frontend.getCategory', 'bidang-tata-ruang'),
        'type' => 'category',
        'type_id' => 3,
        'order' => 99,
        'has_child' => 0,
        'parent_id' => 9,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Bidang Cipta Karya',
        'url' => route('frontend.getCategory', 'bidang-cipta-karya'),
        'type' => 'category',
        'type_id' => 4,
        'order' => 99,
        'has_child' => 0,
        'parent_id' => 9,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Bidang Pengembangan Konstruksi',
        'url' => route('frontend.getCategory', 'bidang-pengembangan-konstruksi'),
        'type' => 'category',
        'type_id' => 5,
        'order' => 99,
        'has_child' => 0,
        'parent_id' => 9,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Bidang Sumber Daya Air',
        'url' => route('frontend.getCategory', 'bidang-sumber-daya-air'),
        'type' => 'category',
        'type_id' => 6,
        'order' => 99,
        'has_child' => 0,
        'parent_id' => 9,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
    [
        'title' => 'Kontak',
        'url' => route('kontak'),
        'order' => 6,
        'type' => 'page',
        'type_id' => 7,
        'has_child' => 0,
        'parent_id' => 0,
        'child' => null,
        'created_at' => Carbon::now(),
        'updated_at' => Carbon::now()
    ],
];
